Repository kubecost/kubecost, pull requests merged in 2022-04, with the labels that each got.

#1339 remove deprecated server port
  cost-analyzer/templates/cost-analyzer-service-template.yaml
Labels: bug, next release, needs cherry pick

#1373 Added in Customer Google Tag to values and environment variables
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v1.93

#1344 Fix issue in the helm chart to run multiple kubecost
  cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml
  cost-analyzer/templates/cost-analyzer-cluster-role-template.yaml
  cost-analyzer/templates/network-costs-psp.template.yaml
  cost-analyzer/templates/network-costs-role.template.yaml
  cost-analyzer/templates/network-costs-rolebinding.template.yaml
Labels: next release, v1.93

#1192 Pin local chart dependencies in Chart.yaml files
  cost-analyzer/Chart.yaml
  cost-analyzer/charts/prometheus/Chart.yaml
Labels: next release

#1341 Add maxPrometheusQueryDurationMinutes setting
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: next release, v1.93

#1370 Grafana Enabled Env Var
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: next release, v1.93

#1394 Remove GOGC tuning from Cost-Model
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: next release, v1.93

#1396 Add github action to validate chart
  .github/workflows/chart.yaml
Labels: next release, v1.93
