Repository kubecost/kubecost, pull requests merged in 2022-12, with the labels that each got.

#1828 Fix indentation of network-costs requests/limits
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
Labels: bug, v1.99

#1827 Remove `azureStorageSecretName` from values.yaml.
  cost-analyzer/values.yaml
Labels: bug, v1.99

#1844 Add support for setting Advanced Reports via values.yaml
  cost-analyzer/templates/cost-analyzer-advanced-reports-configmap.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v1.99

#1846 Add cloud cost env variables
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v1.99

#1847 V1.99 patch/cloud cost env
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v1.99

#1845 v1.99 patch/advanced reports
  cost-analyzer/templates/cost-analyzer-advanced-reports-configmap.yaml
  cost-analyzer/values.yaml
Labels: patch, v1.99

#1829 allow additionnal labels in networkcost
  cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values.yaml
Labels: v1.100-proposal

#1682 Replace deprecated kube_pod_container_resource_requests_memory_bytes metric in Pod Utilization grafana dashboard
  cost-analyzer/pod-utilization.json
Labels: needs-triage
