Repository kubecost/kubecost, pull requests merged in 2022-06, with the labels that each got.

#1444 Update cluster-controller to v0.1.0
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: v1.94

#1385 Allow more Prometheus flexibility
  cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
  cost-analyzer/templates/kubecost-metrics-service-template.yaml
  cost-analyzer/values.yaml
Labels: enhancement

#1457 Remove duplicate label configurations on service monitor
  cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml
Labels: v1.95, community

#1496 fix grafana pod utilization dashboard query
  cost-analyzer/pod-utilization.json
Labels: v1.95

#1462 Update app label of exporter service, ServiceMonitor missmatch.
  cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml
  cost-analyzer/templates/kubecost-metrics-service-template.yaml
Labels: v1.95, community
