Repository kubecost/kubecost, pull requests merged in 2022-08, with the labels that each got.

#1587 Prevent duplicate "app" labels when enabling cluster controller
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Labels: v1.96, needs-follow-up

#1602 Add etl store read only mode
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v1.96

#1588 Needs-follow-up fix
  .github/workflows/label-comments.yml
Labels: enhancement, v1.96, needs-follow-up, outside-release

#1599 Warning policy/v1beta1 usage for PodDisruptionBudget
  cost-analyzer/Chart.yaml
  cost-analyzer/README.md
  cost-analyzer/charts/prometheus/templates/alertmanager-pdb.yaml
  cost-analyzer/charts/prometheus/templates/pushgateway-pdb.yaml
  cost-analyzer/charts/prometheus/templates/server-pdb.yaml
  cost-analyzer/charts/thanos/templates/bucket-poddisruptionbudget.yaml
  cost-analyzer/charts/thanos/templates/query-frontend-poddisruptionbudget.yaml
  cost-analyzer/charts/thanos/templates/query-poddisruptionbudget.yaml
Labels: v1.97

#1505 Drop the default clusterID and force adding one
  .github/workflows/chart.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: enhancement, v1.95, configuration

#1619 Whitelisting new pv volume metrics kubecost_pv_info
  cost-analyzer/charts/prometheus/values.yaml
Labels: v1.97
