Repository kubecost/kubecost, pull requests merged in 2022-07, with the labels that each got.

#1506 Added try_files to / for spa to work.
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v1.95

#1517 Add try_files directive to non-SAML installs. Required for SPA
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: patch, v1.95

#1513 Upgrade prometheus to 2.35.0 and node-exporter to 1.3.0
  cost-analyzer/charts/prometheus/values.yaml
Labels: v1.96

#1509 Add OIDC config params in Values
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/cost-analyzer-oidc-config-map-template.yaml
  cost-analyzer/templates/kubecost-oidc-secret-template.yaml
  cost-analyzer/values.yaml
Labels: v1.95

#1570 add etl cloud query window days var to chart
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v1.96, reliability

#1584 update values file for EKS
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: needs-follow-up

#1568 Leader/Follower Enable
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-cluster-role-template.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v1.96

#1561 Update values.yaml
  cost-analyzer/charts/grafana/values.yaml
Labels: v1.96, needs-follow-up
