Repository kubecost/kubecost, pull requests merged in 2022-02, with the labels that each got.

#1239 Remove trim whitespace hyphen on app label (cherry-pick)
  cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
Labels: patch

#1196 Allow UpdateStrategy Passthrough on Network Costs
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values.yaml
Labels: enhancement

#1267 Revert "Change method of checking if networking.k8s.io/v1/Ingress is …
  cost-analyzer/templates/cost-analyzer-ingress-template.yaml
Labels: next release, patch, needs cherry pick
