Repository kubecost/kubecost, pull requests merged in 2023-05, with the labels that each got.

#2208 Cherry pick EV-59 for v1.103
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/query-service-cluster-role-binding-template.yaml
  cost-analyzer/templates/query-service-cluster-role-template.yaml
  cost-analyzer/templates/query-service-deployment-template.yaml
  cost-analyzer/templates/query-service-service-account-template.yaml
  cost-analyzer/templates/query-service-service-template.yaml
  cost-analyzer/values.yaml
Labels: needs-follow-up

#2209 Add schema for status to TurndownSchedule CRD
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Labels: needs cherry pick, v1.103

#2224 Move multi cloud secret mount path
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
Labels: v1.104

#2239 Continuous Cluster Sizing
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Labels: v1.104

#2246 Update Cluster Controller to v0.8.0
  cost-analyzer/values.yaml
Labels: v1.104

#2249 explicitly cast query service replicas to int
  cost-analyzer/templates/query-service-cluster-role-binding-template.yaml
  cost-analyzer/templates/query-service-cluster-role-template.yaml
  cost-analyzer/templates/query-service-deployment-template.yaml
  cost-analyzer/templates/query-service-service-account-template.yaml
  cost-analyzer/templates/query-service-service-template.yaml
Labels: patch, v1.103

#2260 Update Cluster Controller to v0.9.0
  cost-analyzer/values.yaml
Labels: v1.104

#2266 Enable Cloud Cost by default
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v1.104

#2287 Update Cluster Controller to v0.11.0
  cost-analyzer/values.yaml
Labels: needs cherry pick, v1.104
