Repository kubecost/kubecost, pull requests merged in 2023-11, with the labels that each got.

#2723 add SA
  cost-analyzer/templates/etl-utils-deployment.yaml
Labels: needs cherry pick

#2726 Fix Helm test, values linting
  cost-analyzer/templates/tests/basic-health.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick

#2730 root user compatibility defaults
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: needs cherry pick

#2733 fix and improve basic-health test
  cost-analyzer/templates/tests/basic-health.yaml
Labels: needs cherry pick

#2741 fix networkCosts labels
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v1.107

#2700 prometheus image update
  cost-analyzer/charts/prometheus/values.yaml
Labels: 1.108
