Repository kubecost/kubecost, pull requests merged in 2023-01, with the labels that each got.

#1856 Add Prometheus server ServiceAccount annotations to values.yaml
  cost-analyzer/charts/prometheus/README.md
  cost-analyzer/charts/prometheus/templates/server-serviceaccount.yaml
  cost-analyzer/charts/prometheus/values.yaml
Labels: v1.100

#1789 fix kubecost metrics service wrong app label
  cost-analyzer/templates/kubecost-metrics-service-template.yaml
Labels: v1.100-proposal

#1928 Update cluster-controller to v0.6.0
  cost-analyzer/values.yaml
Labels: v1.100

#1898 add budgetcontroller scaffolding
  cost-analyzer/templates/budget-controller-service-template.yaml
  cost-analyzer/templates/budget-controller-template.yaml
Labels: P0, v1.100

#1936 Change flat manifest link from master to develop
  README.md
Labels: v1.100

#1937 Re-Templated kubecost.yaml to support 1.25+ clusters.
  kubecost.yaml
Labels: v1.100
