Repository kubecost/kubecost, pull requests merged in 2024-01, with the labels that each got.

#2939 Forecasting and anomaly detection
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/forecasting-deployment.yaml
  cost-analyzer/templates/forecasting-service.yaml
  cost-analyzer/values.yaml
Labels: v2.0.0

#2954 Unset DB memory limit
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0.0

#2953 Create emptyDir to fix permissions problem on /var/configs/waterfowl in Aggregator StatefulSet configuration
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0.0

#2957 Add http:// protocol to forecasting base URL
  cost-analyzer/templates/forecasting-deployment.yaml
Labels: needs cherry pick, v2.0.0

#2967 Set Gunicorn worker timeout to 1200 seconds
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2971 Update modeling image with fixed training of Cloud Costs, Assets, and Allocations
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2973 Update modeling image: resilient to bad training data and CC endpoint behavior
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2976 Sensible error on /forecasting if forecasting is disabled (instead of index.html)
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: needs cherry pick, v2.0

#2979 Bump forecasting image with latest improvements
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2982 ssoEnabled flag
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: needs cherry pick, v2.0

#2984 Bump forecasting with error codes update
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2975 multi-cluster prometheus check
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2995 federatedETL agent
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/grafana-attached-disk-metrics-template.yaml
  cost-analyzer/templates/grafana-clusterrole.yaml
  cost-analyzer/templates/grafana-clusterrolebinding.yaml
  cost-analyzer/templates/grafana-configmap-dashboard-provider.yaml
  cost-analyzer/templates/grafana-configmap.yaml
  cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml
  cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-kubernetes-resource-efficiency-template.yaml
  cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-prometheus-metrics-template.yaml
  cost-analyzer/templates/grafana-dashboards-json-configmap.yaml
  cost-analyzer/templates/grafana-deployment.yaml
  cost-analyzer/templates/grafana-ingress.yaml
  cost-analyzer/templates/grafana-networkcosts-metrics-template.yaml
  cost-analyzer/templates/grafana-pod-utilization-multi-cluster-template.yaml
  cost-analyzer/templates/grafana-pvc.yaml
  cost-analyzer/templates/grafana-secret.yaml
  cost-analyzer/templates/grafana-service.yaml
  cost-analyzer/templates/grafana-serviceaccount.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2994 disable configmapReloader by default
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#2986 Move 2.0 precondition checks into a function
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.0

#2998 block thanos agent upgrades and suggest fedetl
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/kubecost-agent-secretprovider-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
Labels: needs cherry pick, v2.0

#3005 Update to check if saml is enabled, not just if the object exists.
  cost-analyzer/templates/kubecost-saml-secret-template.yaml
Labels: needs cherry pick, v2.0

#3006 [GTM-199] take global annotations setting into etlutils
  cost-analyzer/templates/etl-utils-deployment.yaml
Labels: needs cherry pick, v2.0

#3010 Enable forecasting by default, fix "early spike" forecast behavior
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#3023 Bumped image tag with tighter prediction interval
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#3027 updated release note
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.0

#3029 remove forecasting when agentOnly
  cost-analyzer/templates/forecasting-deployment.yaml
  cost-analyzer/templates/forecasting-service.yaml
Labels: needs cherry pick, v2.0

#3031 fix link
  cost-analyzer/templates/NOTES.txt
Labels: needs cherry pick, v2.0

#3039 add upstream for singlepod
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: needs cherry pick, v2.0

#3034 Bump image with retraining fixes
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0
