Repository kubecost/kubecost, pull requests merged in 2024-04, with the labels that each got.

#3298 Fix Grafana SA not creating (#3297)
  cost-analyzer/templates/grafana-serviceaccount.yaml
Labels: needs cherry pick, v2.1, v2.2

#3303 fix ext-costs config
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.2

#3309 remove reference to deprecated env variables
  cost-analyzer/ci/federatedetl-primary-netcosts-values.yaml
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: v2.3

#3311 update helm note
  cost-analyzer/templates/NOTES.txt
Labels: needs cherry pick, v2.2

#3313 bump kubecost-modeling fixing xz vulnerability CVE-2024-3094
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1, v2.2

#3305 Changes to add security context for cloud-cost
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
Labels: needs cherry pick, v2.1, v2.2

#3331 quick fix for athena cc integration on single pod deployments
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v2.2

#3324 disable helm-rollout-restarter if cicd=true
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/diagnostics-deployment.yaml
  cost-analyzer/templates/frontend-deployment-template.yaml
  cost-analyzer/templates/prometheus-server-deployment.yaml
Labels: v2.3

#3336 Add env variable to cloud-cost template
  cost-analyzer/templates/_helpers.tpl
Labels: v2.2

#3335 Add env variable to cloud-cost template
  cost-analyzer/templates/_helpers.tpl
Labels: v2.2

#3334 add READ_ONLY to aggregator
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1, v2.2

#3348 clusterIDCheck
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
Labels: v2.3

#3238 Kubecost Integrations - Postgres
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/integrations-postgres-queries-configmap.yaml
  cost-analyzer/templates/integrations-postgres-secret.yaml
  cost-analyzer/values.yaml
Labels: v2.3

#3364 Update error message with more explicit instructions
  cost-analyzer/templates/_helpers.tpl
Labels: v2.3

#3365 Add comments specifying that all params must be enclosed in quotes.
  cost-analyzer/values.yaml
Labels: v2.3
