Repository kubecost/kubecost, pull requests merged in 2024-08, with the labels that each got.

#3575 Resolved issue where aggregator pod fails due to missing smtp-secret volume
  cost-analyzer/templates/aggregator-statefulset.yaml
Labels: bug, v2.3

#3592 bump cluster-controller CVE-2024-41110 fix
  cost-analyzer/values.yaml
Labels: v2.3, needs cherry-pick

#3615 bump modeling 0.1.15 CVE-2024-7592
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: v2.3, v2.4, needs cherry-pick
