Repository kubecost/kubecost, pull requests merged in 2024-07, with the labels that each got.

#3546 bump cluster controller to v0.16.5
  cost-analyzer/values.yaml
Labels: v2.3, needs cherry-pick

#3538 Add extraScrapeConfig to scrape DCGM Exporter
  cost-analyzer/values.yaml
Labels: v2.4

#3516 add options to hide ui elements
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v2.4

#3552 aggregator etlHourlyStoreDurationHours
  cost-analyzer/templates/_helpers.tpl
Labels: v2.4

#3559 Bump Prometheus from v2.52.0 to v2.53.1
  cost-analyzer/values.yaml
Labels: dependencies, docker, v2.4

#3553 Advanced Reports has been removed from product.
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-advanced-reports-configmap.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v2.4

#3564 fix grafana enabled bool on aggregator
  cost-analyzer/templates/_helpers.tpl
Labels: v2.3, needs cherry-pick
