Repository kubecost/kubecost, pull requests merged in 2024-12, with the labels that each got.

#3731 correct settting log level in readme
  README.md
  cost-analyzer/README.md
Labels: v2.5

#3764 bump to kiwigrid 1.28.1
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: needs cherry-pick, v2.5

#3763 add init container for updating ca trust and shift getting ca cert from secret to config map
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.5

#3773 bump cluster-controller
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.5

#3781 Remove-old-api-port
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: bug, v2.6
