Repository kubecost/kubecost, pull requests merged in 2024-02, with the labels that each got.

#3051 EKS values for 2.0
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: needs cherry pick, v2.0

#3049 [SELFHOST-1141] Atm/selfhost 1141 yaml actions
  cost-analyzer/templates/kubecost-cluster-controller-actions-configmap.yaml
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick

#3056 Add error messages
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#3048 Add sanity check for cloudIntegrationSecret
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.0

#3053 Fix duplicate labels key in metadata in aggregator StatefulSet
  cost-analyzer/templates/aggregator-statefulset.yaml
Labels: needs cherry pick, v2.0

#3061 update structure, improve example values
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#3055 Cloud Integration Update
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/cloud-integration-secret.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0

#3085 add athenaWorkgroup and masterPayerARN
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.0, v2.1

#3083 Add CICD option to platforms with skipSanityChecks
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.0, v2.1

#3097 EKS values image bumps
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: v2.0, v2.1

#3102 Multi-cluster Diagnostics runs in the cost-model by default
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/diagnostics-deployment.yaml
  cost-analyzer/templates/diagnostics-service.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1

#3101 nginx - add service accounts routes
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.1

#3088 feat: Allow templating fqdn for all frontend upstreams
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1

#3107 Expose new data diagnostic APIs
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.1

#3098 Add sanity/existence check for `kubecostModel.federatedStorageConfigSecret`
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: v2.1

#3127 Pagination limit control for forecasting
  cost-analyzer/templates/forecasting-deployment.yaml
Labels: needs cherry pick, v2.1

#3131 bump forecasting version
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1

#3138 Atm/bump clust turndown
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: needs cherry pick, v2.1

#3118 Add labels for basic-health tester Pod
  cost-analyzer/templates/tests/basic-health.yaml
Labels: needs cherry pick, v1.108, v2.0, v2.1

#3120 Adopt fullnameOverride for cost-analyzer Service
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-service-template.yaml
Labels: needs cherry pick, v2.1

#3147 else if etlBucketConfigSecret
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.1

#3066 additional checks for 2.0: leader-follower, statefulSet, cloud-integration configs
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/cloud-integration-secret.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
Labels: needs cherry pick, v2.0, v2.1

#3152 Introduce more data diagnostic endpoints for table windows, nodes per day, and container label/annotation statistics
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.1

#3145 dataBackupConfigured flag
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: needs cherry pick, v2.1

#3154 fix logic
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.0, v2.1

#3067 fix multi-cluster pod utilization dashboard
  cost-analyzer/grafana-templates/multi-cluster-container-stats.json
  cost-analyzer/pod-utilization-multi-cluster.json
Labels: needs cherry pick, v2.1

#3094 Route the integration validate endpoint to the cloud cost container
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.2

#3161 Add loadBalancerSourceRanges for Cost Analyser service
  cost-analyzer/templates/cost-analyzer-service-template.yaml
  cost-analyzer/values.yaml
Labels: v2.2

#3167 Reduce Prom retention to 97h for stability
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: v2.2

#3179 correct image name in values-eks-cost-monitoring.yaml
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: needs cherry pick, v2.1
