Repository kubecost/kubecost, pull requests merged in 2024-03, with the labels that each got.

#3194 Bump forecasting image
  cost-analyzer/values.yaml
Labels: v2.2

#3073 FIX grafana service account creation and name
  cost-analyzer/README.md
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1, v2.2

#3196 Misc cleanup
  README.md
  cost-analyzer/Chart.yaml
  cost-analyzer/old-grafana-values.yaml
  cost-analyzer/old-prometheus-values.yaml
Labels: v2.2

#3188 Fix MultiCluster Diagnostics bug when run in cost-model
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: v2.2

#3190 Route /model/savings/clusterSizingETL to Aggregator
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.2

#3206 Add log level to network costs
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.1, v2.2

#3209 improve cloudCost logic with aggregator
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/aggregator-cloud-cost-service-account.yaml
  cost-analyzer/templates/aggregator-cloud-cost-service.yaml
Labels: v2.2

#3211 add flag for costEventsAudit
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.2

#3239 Add filter-based config to the Helm ("YAML") Actions config
  cost-analyzer/values.yaml
Labels: v2.2

#3252 Fix Kubecost UI stuck at 'Oh No!' for SAML users after upgrade
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Labels: needs cherry pick, v2.1, v2.2

#3257 bump modeling image 0.1.5
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.2

#3278 Change default log level of network costs to info
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.2

#3282 pluginsEnabled boolean
  cost-analyzer/templates/_helpers.tpl
Labels: needs cherry pick, v2.2

#3266 Simplify EKS values
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: needs cherry pick, v2.2

#3275 v2.2 #3273 cherry pick
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v2.2

#3274 v2.1 #3273 cherry pick
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v2.1

#3287 Minor values nits
  cost-analyzer/values.yaml
Labels: needs cherry pick, v2.2

#3291 fix bug #3219
  cost-analyzer/templates/grafana-attached-disk-metrics-template.yaml
  cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml
  cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-kubernetes-resource-efficiency-template.yaml
  cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml
  cost-analyzer/templates/grafana-dashboard-prometheus-metrics-template.yaml
  cost-analyzer/templates/grafana-networkcosts-metrics-template.yaml
  cost-analyzer/templates/grafana-pod-utilization-multi-cluster-template.yaml
Labels: v2.3

#3283 carbonEstimatesEnabled boolean
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.3
