Repository kubecost/kubecost, pull requests merged in 2024-11, with the labels that each got.

#3732 Turbo-fix
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/integrations-turbonomic-secret.yaml
Labels: bug, v2.5

#3741 resolve issue with prometheus pull
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: v2.4, needs cherry-pick

#3742 fix link
  .gitignore
  cost-analyzer/values.yaml
Labels: v2.4

#3721 fix openshift values to default with in-cluster prometheus
  cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml
  cost-analyzer/templates/monitoring-role-binding-template.yaml
  cost-analyzer/values-openshift-cluster-prometheus.yaml
  cost-analyzer/values-openshift.yaml
  cost-analyzer/values.yaml
Labels: enhancement, needs cherry-pick, v2.5
