Repository kubecost/kubecost, pull requests merged in 2024-09, with the labels that each got.

#3637 fix diagnostics and federatedStorageConfig
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/diagnostics-deployment.yaml
  cost-analyzer/templates/diagnostics-service.yaml
  cost-analyzer/templates/etl-utils-deployment.yaml
Labels: v2.4, needs cherry-pick

#3647 tmp dir for new base image
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/frontend-deployment-template.yaml
Labels: v2.4, needs cherry-pick

#3652 bump cluster-controller 0.16.9
  cost-analyzer/values.yaml
Labels: v2.3, v2.4, needs cherry-pick

#3655 bump kubecost-modeling 0.1.16
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: v2.3, v2.4, needs cherry-pick

#3658 remove helm rollout restarter
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-cloud-cost-deployment.yaml
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/diagnostics-deployment.yaml
  cost-analyzer/templates/frontend-deployment-template.yaml
  cost-analyzer/templates/prometheus-server-deployment.yaml
  kubecost.yaml
Labels: v2.4, needs cherry-pick

#3660 Enhance Pod utilization Grafana dashboard with GPU utilization widget
  cost-analyzer/grafana-dashboards/pod-utilization.json
Labels: v2.4, needs cherry-pick

#3662 bump network-costs 0.17.6
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: v2.3, v2.4, needs cherry-pick

#3642 Add new container costs and resources endpoints to nginx
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v2.4, needs cherry-pick

#3673 add warning for federated storage
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
Labels: v2.4

#3680 [CI] Test with K8s 1.31
  .github/workflows/chart.yaml
  README.md
Labels: v2.4, needs cherry-pick

#3684 ENG-2851 - Add `/diagnostic/nodeCount` endpoint
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.4, needs cherry-pick

#3585 Add missing container security context in prometheus server statefulset
  cost-analyzer/templates/prometheus-server-statefulset.yaml
Labels: v2.4, needs cherry-pick

#3679 Allow defining resources for Cluster Controller
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: v2.4, needs cherry-pick
