Repository kubecost/kubecost, pull requests merged in 2025-03, with the labels that each got.

#3913 Bump cluster-controller to v0.16.14
  cost-analyzer/values.yaml
Labels: v2.7

#3910 Teams config example
  .lycheeignore
  cost-analyzer/values-teams-example-config.yaml
Labels: v2.6

#3921 CP 2.5 Bump prometheus from v2.55.1 to v3.2.1 to fix CVEs
  cost-analyzer/values.yaml
Labels: v2.5

#3916 Set runAsUser=0 for network-costs daemonset
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
Labels: v2.7

#3397 Default-enable Multi Cluster Diagnostics
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/diagnostics-deployment.yaml
  cost-analyzer/values.yaml
Labels: v2.7

#3922 Request Sizing Profiles saved on PV and Expose GET, POST, and DELETE Operations with Values from Helm
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/templates/savings-profiles-configmap.yaml
  cost-analyzer/values.yaml
Labels: v2.7

#3946 25-image-bumps
  cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: v2.5

#3941 Removes GCP Marketplace install from Helm chart
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/gcpstore-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v2.7

#3958 remove tags from eks values file
  cost-analyzer/values-eks-cost-monitoring.yaml
Labels: v2.7

#3962 add helm flag to allow opt-in to new DB
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values.yaml
Labels: v2.8.0

#3968 Replace docs links with IBM
  cost-analyzer/README.md
  cost-analyzer/ci/federatedetl-primary-netcosts-values.yaml
  cost-analyzer/grafana-dashboards/README.md
  cost-analyzer/grafana-dashboards/grafana-templates/multi-cluster-network-transfer-data.json
  cost-analyzer/grafana-dashboards/networkCosts-metrics.json
  cost-analyzer/templates/NOTES.txt
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values-openshift-cluster-prometheus.yaml
  cost-analyzer/values-teams-example-config.yaml
  cost-analyzer/values.yaml
Labels: v2.7

#3967 Remove hostPort from cluster-controller
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Labels: needs cherry-pick, v2.6, v2.7

#3969 update chart build tests - k8s version bumps
  .github/workflows/chart.yaml
  README.md
Labels: v2.8
