Repository kubecost/kubecost, pull requests merged in 2025-02, with the labels that each got.

#3835 add labels, securityContext and image pull secret in cluster controller
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.6

#3839 bump cluster-controller v0.16.12
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.5, v2.6

#3784 add helm values for cluster controller primary access from secondary
  .lycheeignore
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.6

#3858 bump cluster controller to v0.16.13
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.5, v2.6

#3863 Refactor forecasting template
  cost-analyzer/templates/forecasting-deployment.yaml
  cost-analyzer/values-eks-cost-monitoring.yaml
  cost-analyzer/values.yaml
Labels: enhancement, v2.7

#3880 Fix repo for kubecost-modeling
  cost-analyzer/values.yaml
Labels: v2.7

#3879 Update kubecost.yaml and cost-analyzer/values.yaml to target v0.1.22 of the kubecost-modeling image
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: needs cherry-pick, v2.6

#3886 add extraEnv and logLevel in helm values for clusterController
  cost-analyzer/templates/kubecost-cluster-controller-template.yaml
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.6

#3904 [KCM-3366] Restrict CORS headers
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.7

#3906 nginx routing for category sharing endpoints
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.7

#3901 KCM-3462: allow user to provide custom labels to append each provider's default nodegroup label using helm to identify nodegroups in their setup
  cost-analyzer/templates/savings-recommendations-nodegroup-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v2.7

#3911 Prevent installing Grafana dashboards when Grafana is disabled
  cost-analyzer/templates/grafana/grafana-dashboard-attached-disks.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-cluster-metrics-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-cluster-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-deployment-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-kubernetes-resource-efficiency-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-label-cost-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-namespace-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-network-cloud-sevices.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-network-costs.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-node-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-pod-utilization-multi-cluster.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-pod-utilization-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-prometheus-metrics-template.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-workload-aggregator.yaml
  cost-analyzer/templates/grafana/grafana-dashboard-workload-metrics.yaml
Labels: v2.7
