Repository kubecost/kubecost, pull requests merged in 2025-06, with the labels that each got.

#4094 [KCM-3819] return only version info in installInfo response
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v3.0

#4095 Cleanup and remove old files
  README.md
  cost-analyzer/Chart.yaml
  historical-builds/README.md
  kubecost.yaml
  kustomization.yaml
Labels: v3.0

#4097 provide a way to configure FE defaults via helm
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v3.0

#4090 custom json of instance types mounted in aggregator statefulset to be populated into the DB
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values-instance-types.yaml
  cost-analyzer/values.yaml
Labels: v3.0

#4102 KCM-4211 Added imagePullSecrets for Grafana Mimir
  cost-analyzer/templates/mimir-proxy-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: enhancement, v2.8

#4113 bump version, add LOG_LEVEL
  cost-analyzer/values.yaml
Labels: needs cherry-pick, security fix, v2.7, v2.8.0, v2.8

#4116 fix cluster-controller CVE
  cost-analyzer/values.yaml
Labels: needs cherry-pick, security fix, v2.7, v2.8.0, v2.8

#4110 [KCM-4014] revamp the license file to support v2 licensing
  .github/workflows/chart.yaml
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-pkey-secret.yaml
  cost-analyzer/values.yaml
Labels: v3.0

#4126 create the volume mount when key enabled
  cost-analyzer/ci/aggregator-values.yaml
  cost-analyzer/ci/federatedetl-primary-netcosts-values.yaml
  cost-analyzer/ci/statefulsets-cc.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v3.0

#4125 [KCM-3944] Actions: Set up bucket storage
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/actions-config-configmap-template.yaml
  cost-analyzer/templates/actions-store-secret.yaml
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
Labels: v3.0
