Repository kubecost/kubecost, pull requests merged in 2025-04, with the labels that each got.

#4004 Bump network costs image version
  cost-analyzer/values.yaml
Labels: v2.8

#3683 Remove `containerStatsEnabled` from values files
  cost-analyzer/ci/federatedetl-primary-netcosts-values.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/values.yaml
  kubecost.yaml
Labels: v2.8

#4015 [KCM-3988] Make CSP more permissive by default
  cost-analyzer/values.yaml
Labels: bug, needs cherry-pick, v2.7, v2.8.0, v2.8

#4031 bump modeling for cve fix
  kubecost.yaml
Labels: needs cherry-pick, v2.6, v2.7, v2.8

#4035 bump cluster-controller to v0.16.18
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.7, v2.8
