Repository kubecost/kubecost, pull requests merged in 2025-08, with the labels that each got.

#4145 [KCM-3942] Pass "ACTIONS_ENABLED" env var to Aggregator
  .lycheeignore
  kubecost/templates/aggregator/aggregator-statefulset.yaml
Labels: v3.0

#4171 Bump Grafana and Prometheus to address CVEs
  cost-analyzer/values.yaml
Labels: v2.8

#4180 Atm/kcm 4354
  kubecost/templates/aggregator/aggregator-statefulset.yaml
  kubecost/values.yaml
Labels: v3.0

#4184 fix mounting issues
  kubecost/templates/aggregator/aggregator-statefulset.yaml
Labels: v3.0

#4189 remove hard-coded aggregator resource limits
  kubecost/values.yaml
Labels: v3.0

#4193 add missing ,
  kubecost/templates/frontend/frontend-configmap.yaml
Labels: bug, v3.0

#4194 finops-agent compatibility
  kubecost/templates/NOTES.txt
  kubecost/templates/_helpers.tpl
  kubecost/templates/frontend/frontend-configmap.yaml
  kubecost/templates/local-store/_helpers.tpl
  kubecost/templates/local-store/cluster-storage-pvc.yaml
  kubecost/values.yaml
Labels: v3.0

#4196 existingSecretName rename
  .github/ci-helmValues/helmValues-federated-store.yaml
  kubecost/ci/aggregator-values.yaml
  kubecost/ci/federatedetl-primary-netcosts-values.yaml
  kubecost/templates/NOTES.txt
  kubecost/templates/_helpers.tpl
  kubecost/templates/aggregator/aggregator-statefulset.yaml
  kubecost/templates/local-store/_helpers.tpl
  kubecost/values.yaml
Labels: v3.0

#4197 add example helm action config
  kubecost/values.yaml
Labels: v3.0

#4204 allow custom forecasting sa
  kubecost/templates/forecasting/forecasting-deployment.yaml
  kubecost/values.yaml
Labels: v3.0

#4205 v2.8 fix check for nulls on /getConfigs
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Labels: v2.8, 2.8.3

#4218 readme edits
  examples/README.md
Labels: v3.0

#4219 readme
  examples/README.md
Labels: v3.0

#4222 add image values
  kubecost/values.yaml
Labels: needs cherry-pick, v3.0

#4223 [KCM-4382] Link log collection Role to RoleBinding
  kubecost/templates/kubecost-role-binding-template.yaml
Labels: v3.0

#4220 readme edits
  README.md
  examples/agentOnly/helmValues-kubecost-aws.yaml
  examples/agentOnly/helmValues-kubecost-azure.yaml
  examples/agentOnly/helmValues-kubecost-gcp.yaml
  kubecost/README.md
Labels: v3.0

#4225 [KCM-4382] Log collection: Set up Role/RoleBinding for aggregator SA
  kubecost/templates/aggregator/aggregator-role-binding.yaml
  kubecost/templates/aggregator/aggregator-role.yaml
  kubecost/templates/kubecost-role-binding-template.yaml
  kubecost/templates/kubecost-role-template.yaml
Labels: v3.0

#4215 Update helm chart testing 3.0
  .github/ci-files/actionsStorageBucket.yaml
  .github/ci-files/federatedStorageConfigSecret.yaml
  .github/workflows/test-chart-2.x.yml
  .github/workflows/test-chart-3.0.yml
  .gitignore
  kubecost/ci/aggregator-values.yaml
  kubecost/ci/federatedetl-primary-netcosts-values.yaml
  kubecost/ci/statefulsets-cc.yaml
  kubecost/templates/local-store/cluster-storage-deployment.yaml
  kubecost/templates/tests/basic-health.yaml
  kubecost/values-eks-cost-monitoring.yaml
Labels: v3.0
