Repository kubecost/kubecost, pull requests merged in 2025-05, with the labels that each got.

#4040 cancel-in-progress action on chart test
  .github/workflows/chart.yaml
Labels: needs cherry-pick, v2.6, v2.7, v2.8

#3898 Add new configuration for CSV custom pricing on primary
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/templates/aggregator-statefulset.yaml
  cost-analyzer/templates/cost-analyzer-deployment-template.yaml
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values-enterprise-custom-pricing.yaml
  cost-analyzer/values.yaml
Labels: v2.8.0, v2.8

#4066 Add a Github Action that will require PRs to have a label for the target version of the product
  .github/workflows/check_pr_labels.yaml
Labels: v3.0

#4065 remove node exporter test
  .github/workflows/chart.yaml
Labels: github_actions, needs cherry-pick, v2.7, v2.8

#4060 Add unified agent access needs to cluster role
  cost-analyzer/templates/cost-analyzer-cluster-role-template.yaml
Labels: v3.0

#4076 fix a number of DAST scan alerts
  cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
  cost-analyzer/values.yaml
Labels: v3.0

#4084 update applyRetroactively
  cost-analyzer/templates/_helpers.tpl
  cost-analyzer/values-enterprise-custom-pricing.yaml
  cost-analyzer/values.yaml
Labels: needs cherry-pick, v2.8
